
{% set data = load_setup_py_data() %}

package:
  name: celescope
#  version: {{ data['version'] }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}
  entry_points:
    {% for entry in data['entry_points']['console_scripts'] %}
      - {{ entry.split('=')[0].strip() }} = {{ entry.split('=')[1].strip() }}
    {% endfor %}

extra:
  channels:
    - conda-forge
    - bioconda

requirements:
  host:
    - python ==3.7.6
    - pip
  run:
    - python ==3.7.6
    - star ==2.7.3a
    - fastqc ==0.11.9
    - picard ==2.22.8
    - ucsc-gtftogenepred ==377
    - subread ==2.0.0
    - samtools ==1.9
    # dependencies are defined in setup.py
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    {# raw is for ignoring templating with cookiecutter, leaving it for use with conda-build #}

about:
  home: https://github.com/SingleronBio/SCOPE-tools
  summary: Single Cell Omics Preparation Entity tools
  license: {{ data['license'] }}
  license_file: LICENSE
